version: "3"
services:
    katan-ui:
        image: katanio/ui:latest
        container_name: katan-ui
        ports:
            - "80:80"
        environment:
            - VUE_APP_KATAN_SERVER_API=http://0.0.0.0:1000/
            - VUE_APP_KATAN_SERVER_WS=ws://0.0.0.0:1000/